<a href="https://colab.research.google.com/github/krec7748/Fastcampus_DeepLearning/blob/main/CH01_04_Artificial_Neurons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Shape of Dense Layers

In [16]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.linalg import matmul
from tensorflow.math import exp

N, n_feature = 8, 10
n_neuron = 3
X = tf.random.normal(shape = (N, n_feature))

#Calculate with Tensorflow
dense = Dense(units = n_neuron, activation = "sigmoid")
Y_tf = dense(X)
print("\n Y(Tensorflow): \n", Y_tf.numpy())

#Calculate with matrix multiplication
W, B = dense.get_weights()
Z = matmul(X, W) + B
Y_man_matmul = 1 / (1 + exp(-Z))
print("\n Y(with matrix multiplication): \n", Y_man_matmul.numpy())

#Calculate with dot products
Y_man_vec = np.zeros(shape = (N, n_neuron))
for x_idx in range(N):
    x = X[x_idx]
    for nu_idx in range(n_neuron):
        w, b = W[:, nu_idx], B[nu_idx]
        z = tf.reduce_sum(x * w) + b
        a = 1 / (1 + exp(-z))
        Y_man_vec[x_idx, nu_idx] = a

print("\n Y(with dot products): \n", Y_man_vec)


 Y(Tensorflow): 
 [[0.48164645 0.7551069  0.1126475 ]
 [0.12628874 0.5370229  0.62083703]
 [0.78301036 0.5213088  0.67522556]
 [0.48522928 0.09959453 0.5949204 ]
 [0.5693366  0.64681715 0.47387862]
 [0.37126246 0.5371266  0.5033089 ]
 [0.68942326 0.19829062 0.8204477 ]
 [0.32071602 0.95223856 0.20194769]]

 Y(with matrix multiplication): 
 [[0.48164645 0.7551069  0.11264751]
 [0.12628877 0.53702295 0.62083703]
 [0.7830103  0.5213088  0.67522556]
 [0.48522928 0.09959453 0.5949204 ]
 [0.56933653 0.64681715 0.47387856]
 [0.37126243 0.53712666 0.5033089 ]
 [0.68942326 0.1982906  0.8204477 ]
 [0.32071596 0.9522385  0.20194769]]

 Y(with dot products): 
 [[0.48164651 0.75510693 0.11264749]
 [0.12628874 0.53702295 0.62083697]
 [0.7830103  0.52130878 0.67522556]
 [0.48522928 0.09959453 0.5949204 ]
 [0.56933659 0.64681709 0.47387862]
 [0.37126243 0.5371266  0.50330889]
 [0.68942326 0.1982906  0.82044768]
 [0.32071599 0.9522385  0.20194772]]
