## 1. Shape of Dense Layers

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.linalg import matmul
from tensorflow.math import exp

#Input setting
N, n_feature = 8, 10
X = tf.random.normal(shape = (N, n_feature)) 

#Calculate with Tensorflow
n_neuron = 3
dense = Dense(units = n_neuron, activation = "sigmoid")
Y_tf = dense(X)
print("\n Y(Tensorflow): \n", Y_tf.numpy())

#Calculate with matrix multiplication
W, B = dense.get_weights()
Z = matmul(X, W) + B
Y_man_matmul = 1 / (1 + exp(-Z))
print("\n Y(with matrix multiplication): \n", Y_man_matmul.numpy())

#Calculate with dot products
Y_man_vec = np.zeros(shape = (N, n_neuron))
for x_idx in range(len(X)):
    x = X[x_idx]
    for nu_idx in range(n_neuron):
        w, b = W[:, nu_idx], B[nu_idx]
        z = tf.reduce_sum(x * w) + b
        a = 1 / (1 + np.exp(-z))

        Y_man_vec[x_idx, nu_idx] = a

print("\n Y(with dot products): \n", Y_man_vec)


 Y(Tensorflow): 
 [[0.76005375 0.6495873  0.57668954]
 [0.3407365  0.21456623 0.25230002]
 [0.27884147 0.8648592  0.75246453]
 [0.80794847 0.24586073 0.37539452]
 [0.5476919  0.24417326 0.65613246]
 [0.587125   0.2250002  0.37086973]
 [0.53236616 0.1880568  0.23326704]
 [0.30522463 0.84794647 0.5563816 ]]

 Y(with matrix multiplication): 
 [[0.7600537  0.6495873  0.57668954]
 [0.34073648 0.21456625 0.25230002]
 [0.27884144 0.86485916 0.75246453]
 [0.8079485  0.24586071 0.37539452]
 [0.5476919  0.24417324 0.65613246]
 [0.587125   0.22500019 0.3708697 ]
 [0.5323662  0.18805678 0.23326702]
 [0.30522463 0.84794647 0.55638164]]

 Y(with dot products): 
 [[0.7600537  0.64958733 0.57668956]
 [0.34073652 0.21456624 0.25230006]
 [0.27884144 0.86485923 0.75246452]
 [0.80794849 0.24586072 0.3753945 ]
 [0.54769187 0.24417326 0.65613244]
 [0.58712504 0.22500017 0.37086974]
 [0.53236617 0.18805678 0.23326703]
 [0.3052246  0.84794648 0.5563816 ]]


## 2. Shapes of cascaded Dense Layers

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

#Input setting
N, n_feature = 4, 10
X = tf.random.normal(shape = (N, n_feature))

#Layers setting
n_neurons = [3, 5]
dense_01 = Dense(units = n_neurons[0], activation = "sigmoid")
dense_02 = Dense(units = n_neurons[1], activation = "sigmoid")

#Forward propagation
A1 = dense_01(X)
Y = dense_02(A1)

#Get weight/bias
W1, B1 = dense_01.get_weights()
W2, B2 = dense_02.get_weights()

#Confirm
print("X: {}\n".format(X.shape))

print("W1: ", W1.shape)
print("B1: ", B1.shape)
print("A1: {}\n".format(A1.shape))

print("W2: ", W2.shape)
print("B2: ", B2.shape)
print("Y: {}".format(Y.shape))

X: (4, 10)

W1:  (10, 3)
B1:  (3,)
A1: (4, 3)

W2:  (3, 5)
B2:  (5,)
Y: (4, 5)


## 3. Dense Layers with Python List

In [11]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

#Input setting
N, n_feature = 4, 10
X = tf.random.normal(shape = (N, n_feature))

#Layers setting
n_neurons = [10, 20, 30, 40]
dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units = n_neuron, activation = "relu")
    dense_layers.append(dense)

#Confirm shape
print("Input shape: {} \n".format(X.shape))
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    print("After dense layer", dense_idx + 1)
    print("shape: ", X.shape, "\n")

Y = X

Input shape: (4, 10) 

After dense layer 1
shape:  (4, 10) 

After dense layer 2
shape:  (4, 20) 

After dense layer 3
shape:  (4, 30) 

After dense layer 4
shape:  (4, 40) 



## 4. Output Calculations

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.linalg import matmul
from tensorflow.math import exp

#Input setting
N, n_feature = 4, 10
X = tf.random.normal(shape = (N, n_feature))

#Layers setting
n_neurons = [3, 4, 5]
dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units = n_neuron, activation = "sigmoid")
    dense_layers.append(dense)

#initial variables setting (for manual FP calculation)
X_cp = tf.identity(X) 
W, B = list(), list()

#Forward propagtation (Tensorflow)
for dense_idx, dense in enumerate(dense_layers):

    #FP calculation (tensorflow)
    X = dense(X)

    #Get_weight/bias (for manual FP calculation)
    w, b = dense.get_weights()
    W.append(w)
    B.append(b)

print("Y(Tensorflow): \n {} \n".format(X.numpy()))


#Forward propagation (Manual)
for layer_idx in range(len(n_neurons)):
    w, b = W[layer_idx], B[layer_idx]

    X_cp = matmul(X_cp, w) + b
    X_cp = 1 / (1 + exp(-X_cp))

print("Y(Manual): \n {} \n".format(X_cp.numpy()))

Y(Tensorflow): 
 [[0.61161226 0.49995923 0.43305254 0.575295   0.42242146]
 [0.610527   0.49859464 0.43432337 0.58094877 0.42383298]
 [0.6207511  0.49354452 0.43302143 0.5774702  0.44039056]
 [0.6228132  0.49556866 0.43048415 0.5687875  0.43743366]] 

Y(Manual): 
 [[0.61161226 0.49995923 0.4330525  0.57529503 0.4224214 ]
 [0.610527   0.49859467 0.43432334 0.5809488  0.42383295]
 [0.6207511  0.4935445  0.4330214  0.5774702  0.44039053]
 [0.6228132  0.4955687  0.43048412 0.5687875  0.4374337 ]] 

