<a href="https://colab.research.google.com/github/krec7748/Fastcampus_DeepLearning/blob/main/CH02_Dense_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Shape of Dense Layers

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.linalg import matmul
from tensorflow.math import exp

N, n_feature = 8, 10
n_neuron = 3

#Input setting
X = tf.random.normal(shape = (N, n_feature)) 

#Calculate with Tensorflow
dense = Dense(units = n_neuron, activation = "sigmoid")
Y_tf = dense(X)
print("\n Y(Tensorflow): \n", Y_tf.numpy())

#Calculate with matrix multiplication
W, B = dense.get_weights()
Z = matmul(X, W) + B
Y_man_matmul = 1 / (1 + exp(-Z))
print("\n Y(with matrix multiplication): \n", Y_man_matmul.numpy())

#Calculate with dot products
Y_man_vec = np.zeros(shape = (N, n_neuron))
for x_idx in range(len(X)):
    x = X[x_idx]
    for nu_idx in range(n_neuron):
        w, b = W[:, nu_idx], B[nu_idx]
        z = tf.reduce_sum(x * w) + b
        a = 1 / (1 + np.exp(-z))

        Y_man_vec[x_idx, nu_idx] = a

print("\n Y(with dot products): \n", Y_man_vec)


 Y(Tensorflow): 
 [[0.30751097 0.8209865  0.2935773 ]
 [0.7387432  0.41386208 0.6039121 ]
 [0.8637091  0.16214326 0.8126805 ]
 [0.25348026 0.6437584  0.34383315]
 [0.36160213 0.75704694 0.82105595]
 [0.5724815  0.3141858  0.47363263]
 [0.78053766 0.1680904  0.87203383]
 [0.6653631  0.5261775  0.5975285 ]]

 Y(with matrix multiplication): 
 [[0.30751094 0.82098645 0.29357728]
 [0.73874325 0.41386208 0.6039122 ]
 [0.8637091  0.16214329 0.81268054]
 [0.25348026 0.64375836 0.34383312]
 [0.36160213 0.7570469  0.8210559 ]
 [0.5724815  0.3141858  0.47363263]
 [0.7805377  0.1680904  0.87203383]
 [0.66536313 0.5261775  0.59752846]]

 Y(with dot products): 
 [[0.30751096 0.82098649 0.2935773 ]
 [0.7387432  0.41386207 0.60391211]
 [0.86370907 0.1621433  0.81268054]
 [0.25348027 0.64375842 0.34383313]
 [0.36160214 0.75704694 0.82105596]
 [0.5724815  0.31418579 0.47363263]
 [0.78053764 0.16809042 0.87203379]
 [0.66536314 0.5261775  0.59752851]]


## 2. Shapes of cascaded Dense Layers

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
n_neurons = [3, 5]

#Input setting
X = tf.random.normal(shape = (N, n_feature))

#Layers setting
dense_01 = Dense(units = n_neurons[0], activation = "sigmoid")
dense_02 = Dense(units = n_neurons[1], activation = "sigmoid")

#Forward propagation
A1 = dense_01(X)
Y = dense_02(A1)

#Get weight/bias
W1, B1 = dense_01.get_weights()
W2, B2 = dense_02.get_weights()

#Confirm
print("X: {}\n".format(X.shape))

print("W1: ", W1.shape)
print("B1: ", B1.shape)
print("A1: {}\n".format(A1.shape))

print("W2: ", W2.shape)
print("B2: ", B2.shape)
print("Y: {}".format(Y.shape))

X: (4, 10)

W1:  (10, 3)
B1:  (3,)
A1: (4, 3)

W2:  (3, 5)
B2:  (5,)
Y: (4, 5)


## 3. Dense Layers with Python List

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10

#Input setting
X = tf.random.normal(shape = (N, n_feature))

#Layers setting
n_neurons = [10, 20, 30, 40]

dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units = n_neuron, activation = "relu")
    dense_layers.append(dense)

#Confirm shape
print("Input: {} \n".format(X.shape))
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    print("After dense layer", dense_idx + 1)
    print(X.shape, "\n")

Y = X

Input: (4, 10) 

After dense layer 1
(4, 10) 

After dense layer 2
(4, 20) 

After dense layer 3
(4, 30) 

After dense layer 4
(4, 40) 



## 4. Output Calculations

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.linalg import matmul
from tensorflow.math import exp

N, n_feature = 4, 10

#Input setting
X = tf.random.normal(shape = (N, n_feature))

#Layers setting
n_neurons = [3, 4, 5]
dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units = n_neuron, activation = "sigmoid")
    dense_layers.append(dense)

#initial variables setting (for manual FP calculation)
X_cp = tf.identity(X) 
W, B = list(), list()

#Forward propagtation (Tensorflow)
for dense_idx, dense in enumerate(dense_layers):

    #FP calculation (tensorflow)
    X = dense(X)

    #for manual FP calculation
    w, b = dense.get_weights()
    W.append(w)
    B.append(b)

print("Y(Tensorflow): \n {} \n".format(X.numpy()))

#Forward propagation (Manual)
for layer_idx in range(len(n_neurons)):
    w, b = W[layer_idx], B[layer_idx]

    X_cp = matmul(X_cp, w) + b
    X_cp = 1 / (1 + exp(-X_cp))

print("Y(Manual): \n {} \n".format(X_cp.numpy()))

Y(Tensorflow): 
 [[0.61161226 0.49995923 0.43305254 0.575295   0.42242146]
 [0.610527   0.49859464 0.43432337 0.58094877 0.42383298]
 [0.6207511  0.49354452 0.43302143 0.5774702  0.44039056]
 [0.6228132  0.49556866 0.43048415 0.5687875  0.43743366]] 

Y(Manual): 
 [[0.61161226 0.49995923 0.4330525  0.57529503 0.4224214 ]
 [0.610527   0.49859467 0.43432334 0.5809488  0.42383295]
 [0.6207511  0.4935445  0.4330214  0.5774702  0.44039053]
 [0.6228132  0.4955687  0.43048412 0.5687875  0.4374337 ]] 

