<a href="https://colab.research.google.com/github/krec7748/DeepLearning_Study/blob/main/CH04_Loss_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Datasets

### 1. Dataset for Regression

In [3]:
import tensorflow as tf

N, n_feature = 8, 5
t_weights = tf.constant([1, 2, 3, 4, 5], dtype = tf.float32)
t_bias = tf.constant([10], dtype = tf.float32)

X = tf.random.normal(mean = 0, stddev = 1, shape = (N, n_feature))
Y = tf.reduce_sum(X * t_weights, axis = 1) + t_bias

print("X(shape/dtype/data: {} / {}\n{}\n".format(X.shape, X.dtype, X.numpy()))
print("Y(shape/dtype/data: {} / {}\n{}\n".format(Y.shape, Y.dtype, Y.numpy()))

X(shape/dtype/data: (8, 5) / <dtype: 'float32'>
[[-1.0932076   0.41762376  0.21925676 -1.8363866   0.22332442]
 [ 0.7116061  -0.3723116   0.38752878  0.07922354 -0.5662639 ]
 [ 1.4780434  -0.32748026 -1.0089706   1.1436539   0.30361557]
 [-1.5845163  -0.7893859  -0.3003908  -0.0344043   1.4043479 ]
 [-0.40832642 -0.55226296  1.3156672  -1.1206043   2.1794856 ]
 [ 0.04460362  1.5391792   0.0147307   0.27152556 -0.81270844]
 [-0.43061158 -0.7972743  -0.45131305 -1.5139495  -0.69158506]
 [-0.6245552   1.4009515  -0.06055585 -1.1244944  -0.8478695 ]]

Y(shape/dtype/data: (8,) / <dtype: 'float32'>
[ 4.170886   8.615144  13.8888645 12.819662  18.84916   10.189714
 -2.8928223  3.2583551]



### 2. Dataset for Binary Classification

### 3. Dataset for Multi-class Classification

### 4. Dataset Objects