<a href="https://colab.research.google.com/github/krec7748/DeepLearning_Study/blob/main/CH05_Conv_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Conv Layers

### 1. Shapes of Conv Layers

In [5]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 1, 28, 28, 5

#Set number of filter, kernel size
n_filter = 10
k_size = 3

#Create images
images = tf.random.uniform(shape = (N, n_H, n_W, n_C),
                           minval = 0, maxval = 1)

#Create Conv2D layer
conv = Conv2D(filters = n_filter, kernel_size = k_size)

#Results
y = conv(images)

#Get weights/bias
W, B = conv.get_weights()

#Confirm
print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape)

(1, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(1, 26, 26, 10)


### 2. Correlation Calculation

In [19]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 1, 5, 5, 1

#Set number of filter, kernel size
n_filter = 1
k_size = 3

#Create images
images = tf.random.uniform(shape = (N, n_H, n_W, n_C),
                           minval = 0, maxval = 1)

#Correlation calculation (Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size)
y_tf = conv(images)

#Correlation calculation (Manual)
W, B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()

y_manual = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1): #i range
    for j in range(n_W - k_size + 1): #j range
        window = images[i : i + k_size, j : j + k_size] #window
        y_manual[i, j] = np.sum(window * W) + B

#Confirm
print("Y(Tensorflow): \n", y_tf.numpy().squeeze())
print("\n Y(Manual): \n", y_manual)

Y(Tensorflow): 
 [[0.6972715  0.33938426 0.63551223]
 [0.98809856 0.47635928 0.14005513]
 [0.4771306  0.3111035  0.47617805]]

 Y(Manual): 
 [[0.69727147 0.33938423 0.63551223]
 [0.98809862 0.47635925 0.14005513]
 [0.47713059 0.31110349 0.47617808]]


### 3. Correlation with n-channel

In [28]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 1, 5, 5, 3 # n_C = 3 (color(RGB) channel)

#Set number of filter, kernel size
n_filter = 1
k_size = 3

#Create images
images = tf.random.uniform(shape = (N, n_H, n_W, n_C),
                           minval = 0, maxval = 1)

#Correlation calculation (Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size)
y_tf = conv(images)

#Correlation calculation (Manual)
W, B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1): #i range
    for j in range(n_W - k_size + 1): #j range
        window = images[i : i + k_size, j : j + k_size, :] #window (with color channel)
        y_man[i, j] = np.sum(window * W) + B

#Confirm
print("Y(Tensorflow): \n", y_tf.numpy().squeeze())
print("\n Y(Manual): \n", y_man)

Y(Tensorflow): 
 [[-0.81768936 -1.1135918  -1.041575  ]
 [-1.5700622  -0.9934208  -0.9958805 ]
 [-0.7332578  -0.8833355  -0.76170117]]

 Y(Manual): 
 [[-0.8176893  -1.11359191 -1.04157495]
 [-1.57006228 -0.99342078 -0.99588048]
 [-0.73325771 -0.88333553 -0.76170099]]


## 2. Conv Layer with Filters

### 1. Shapes with Filters

In [12]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 32, 28, 28, 5

#Set number of filter, kernel size
n_filter = 10
k_size = 3

#Create images
images = tf.random.uniform(shape = (N, n_H, n_W, n_C),
                           minval = 0, maxval = 1)

#Create Conv2D layer
conv = Conv2D(filters = n_filter, kernel_size = k_size)

#Results
y = conv(images)

#Get weights/bias
W, B = conv.get_weights()

#Confirm
print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape)

(32, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(32, 26, 26, 10)


### 2. Computations with Filters

In [ ]:
미니배치 1
height 5
width 5
channel 3

필터 갯수 3
커널 사이즈 4

In [17]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 1, 5, 5, 3

#Set number of filter, kernel size
n_filter = 3
k_size = 4

#Create images
images = tf.random.uniform(shape = (N, n_H, n_W, n_C),
                           minval = 0, maxval = 1)

#FP (Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size)
Y_tf = conv(images)

#FP (Manual)
W, B = conv.get_weights()
images = images.numpy().squeeze()
Y_manual = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
    c_W = W[:, :, :, c]
    c_B = B[c]
    for h in range(n_H - k_size + 1):
        for w in range(n_W - k_size + 1):
            window = images[h : h + k_size, w : w + k_size, :]
            Y_manual[h, w, c] = np.sum(window * c_W) + c_B

#Confirm
print("Y(Tensorflow): \n", np.transpose(Y_tf.numpy().squeeze(), (2, 0, 1)))
print("\n Y(Manual): \n", np.transpose(Y_manual, (2, 0, 1)))

Y(Tensorflow): 
 [[[ 0.2979259   0.22504318]
  [ 0.41402733  0.19298813]]

 [[-0.32421777  0.30890673]
  [ 0.19141442  0.3025247 ]]

 [[ 0.16942072 -0.8612787 ]
  [-0.0155199  -0.24261992]]]

 Y(Manual): 
 [[[ 0.29792589  0.22504321]
  [ 0.41402733  0.1929881 ]]

 [[-0.32421777  0.30890679]
  [ 0.19141436  0.30252469]]

 [[ 0.16942078 -0.86127871]
  [-0.01551989 -0.24261993]]]


## 3. Conv Layers with Activation Functions

### 1. Conv Layers with Activation Functions

In [11]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 1, 5, 5, 3

#Set number of filter, kernel size
n_filter = 3
k_size = 4

#Create images
images = tf.random.uniform(minval = 0, maxval = 1,
                           shape = (N, n_H, n_W, n_C))

#FP (Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size, activation = "sigmoid")
Y_tf = conv(images)

#FP (Manual)
W, B = conv.get_weights()
images = images.numpy().squeeze()
Y_manual = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
    c_W = W[:, :, :, c]
    c_b = B[c]
    for h in range(n_H - k_size + 1):
        for w in range(n_W - k_size + 1):
            window = images[h : h + k_size, w : w + k_size, :]
            conv = np.sum(window * c_W) + c_b
            conv = 1 / (1 + np.exp(-conv)) #sigmoid calculation
            
            Y_manual[h, w, c] = conv

#Confirm
print("Y(Tensorflow): \n", np.transpose(Y_tf.numpy().squeeze(), (2, 0, 1)))
print("\n Y(Manual): \n", np.transpose(Y_manual, (2, 0, 1)))

Y(Tensorflow): 
 [[[0.73066634 0.6091009 ]
  [0.7352866  0.6952873 ]]

 [[0.48089778 0.37501237]
  [0.46795678 0.39122283]]

 [[0.5279504  0.59460396]
  [0.59802485 0.6121068 ]]]

 Y(Manual): 
 [[[0.73066637 0.60910084]
  [0.73528662 0.69528734]]

 [[0.48089779 0.37501234]
  [0.46795672 0.3912229 ]]

 [[0.52795041 0.59460393]
  [0.59802484 0.61210681]]]


## 4. Models with Conv Layers

### 1. Models with Sequential Method

In [43]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

#Set number of filters, kernel_size
n_neurons = [10, 20, 30]
k_size = 3

#Create Model
model = Sequential()
model.add(Conv2D(filters = n_neurons[0], kernel_size = k_size, activation = "relu"))
model.add(Conv2D(filters = n_neurons[1], kernel_size = k_size, activation = "relu"))
model.add(Conv2D(filters = n_neurons[2], kernel_size = k_size, activation = "relu"))

#Set input
x = tf.random.normal(shape = (32, 28, 28, 3))

#FP
predictions = model(x)

#Confirm
print("Input: {}".format(x.shape))
print("Output: {}".format(predictions.shape))

print("\n", "=" * 20, "\n")
for layer_idx, layer in enumerate(model.layers):
    W, B = layer.get_weights()
    print("Conv2D Layer_{} W/B shape: \n".format(layer_idx + 1),
          "W: {}, B:{}".format(W.shape, B.shape), "\n")

print("\n", "=" * 20, "\n")
trainable_variables = model.trainable_variables
for train_var_idx, train_var in enumerate(trainable_variables):
    if train_var_idx % 2 == 1:
        continue
    print("Conv2D Layer_{} W/B shape: \n".format(train_var_idx//2 + 1),
          "W: {}, B: {}".format(trainable_variables[train_var_idx].shape,
                                trainable_variables[train_var_idx + 1].shape), "\n")

Input: (32, 28, 28, 3)
Output: (32, 22, 22, 30)


Conv2D Layer_1 W/B shape: 
 W: (3, 3, 3, 10), B:(10,) 

Conv2D Layer_2 W/B shape: 
 W: (3, 3, 10, 20), B:(20,) 

Conv2D Layer_3 W/B shape: 
 W: (3, 3, 20, 30), B:(30,) 



Conv2D Layer_1 W/B shape: 
 W: (3, 3, 3, 10), B: (10,) 

Conv2D Layer_2 W/B shape: 
 W: (3, 3, 10, 20), B: (20,) 

Conv2D Layer_3 W/B shape: 
 W: (3, 3, 20, 30), B: (30,) 



### 2. Models with Model Sub-classing

In [47]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

#Set number of filters, kernel_size
n_neurons = [10, 20, 30]
k_size = 3

#Create model class
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        global n_neurons
        global k_size

        self.conv_layers = []
        for n_neuron in n_neurons:
            self.conv_layers.append(Conv2D(filters = n_neuron, kernel_size = k_size, activation = "relu"))

    def call(self, x):
        #print("Input: ", x.shape)
        #print("\n ==== Conv Layers ==== \n")
        for conv_layer in self.conv_layers:
            x = conv_layer(x)
            W, B = conv_layer.get_weights()
            #print("W/B: {}/{}".format(W.shape, B.shape))
            #print("A: {}\n".format(x.shape))
        return x

model = TestModel()
x = tf.random.normal(shape = (32, 28, 28, 3))
predictions = model(x)
print("Output: ", predictions.shape)

Input:  (32, 28, 28, 3)

 ==== Conv Layers ==== 

W/B: (3, 3, 3, 10)/(10,)
A: (32, 26, 26, 10)

W/B: (3, 3, 10, 20)/(20,)
A: (32, 24, 24, 20)

W/B: (3, 3, 20, 30)/(30,)
A: (32, 22, 22, 30)

Output:  (32, 22, 22, 30)
