<a href="https://colab.research.google.com/github/krec7748/DeepLearning_Study/blob/main/CH05_Conv_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Conv Layers

### 1. Shapes of Conv Layers

In [5]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 1, 28, 28, 5

#Set number of filter, kernel size
n_filter = 10
k_size = 3

#Create images
images = tf.random.uniform(shape = (N, n_H, n_W, n_C),
                           minval = 0, maxval = 1)

#Create Conv2D layer
conv = Conv2D(filters = n_filter, kernel_size = k_size)

#Results
y = conv(images)

#Get weights/bias
W, B = conv.get_weights()

#Confirm
print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape)

(1, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(1, 26, 26, 10)


### 2. Correlation Calculation

In [19]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 1, 5, 5, 1

#Set number of filter, kernel size
n_filter = 1
k_size = 3

#Create images
images = tf.random.uniform(shape = (N, n_H, n_W, n_C),
                           minval = 0, maxval = 1)

#Correlation calculation (Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size)
y_tf = conv(images)

#Correlation calculation (Manual)
W, B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()

y_manual = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1): #i range
    for j in range(n_W - k_size + 1): #j range
        window = images[i : i + k_size, j : j + k_size] #window
        y_manual[i, j] = np.sum(window * W) + B

#Confirm
print("Y(Tensorflow): \n", y_tf.numpy().squeeze())
print("\n Y(Manual): \n", y_manual)

Y(Tensorflow): 
 [[0.6972715  0.33938426 0.63551223]
 [0.98809856 0.47635928 0.14005513]
 [0.4771306  0.3111035  0.47617805]]

 Y(Manual): 
 [[0.69727147 0.33938423 0.63551223]
 [0.98809862 0.47635925 0.14005513]
 [0.47713059 0.31110349 0.47617808]]


### 3. Correlation with n-channel

In [28]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 1, 5, 5, 3 # n_C = 3 (color(RGB) channel)

#Set number of filter, kernel size
n_filter = 1
k_size = 3

#Create images
images = tf.random.uniform(shape = (N, n_H, n_W, n_C),
                           minval = 0, maxval = 1)

#Correlation calculation (Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size)
y_tf = conv(images)

#Correlation calculation (Manual)
W, B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1): #i range
    for j in range(n_W - k_size + 1): #j range
        window = images[i : i + k_size, j : j + k_size, :] #window (with color channel)
        y_man[i, j] = np.sum(window * W) + B

#Confirm
print("Y(Tensorflow): \n", y_tf.numpy().squeeze())
print("\n Y(Manual): \n", y_man)

Y(Tensorflow): 
 [[-0.81768936 -1.1135918  -1.041575  ]
 [-1.5700622  -0.9934208  -0.9958805 ]
 [-0.7332578  -0.8833355  -0.76170117]]

 Y(Manual): 
 [[-0.8176893  -1.11359191 -1.04157495]
 [-1.57006228 -0.99342078 -0.99588048]
 [-0.73325771 -0.88333553 -0.76170099]]
