<a href="https://colab.research.google.com/github/krec7748/DeepLearning_Study/blob/main/CH06_Pooling_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Max/Avg Pooling

### 1. Max Pooling

In [22]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling1D

#Set Length, pooling size, strides
L, f, s = 12, 2, 1

#Input setting
x = tf.random.normal(shape = (1, L, 1))

#Pooling (Tensorflow)
pool_max = MaxPooling1D(pool_size = f, strides = s)
pooled_max_tf = pool_max(x)

#Pooling (Manual)
x = x.numpy().flatten()
pooled_max_manual = np.zeros(shape = (L - f + 1, ))
for i in range(L - f + 1):
    window = x[i : i + f]
    pooled_max_manual[i] = np.max(window)

#Confirm
print("x : {}\n{} \n".format(x.shape, x))
print("Pooled_max(Tensorflow): {}\n{}\n".format(pooled_max_tf.shape, pooled_max_tf.numpy().flatten()))
print("Pooled_max(Manual): {}\n{}\n".format(pooled_max_manual.shape, pooled_max_manual))

x : (12,)
[ 0.16915537 -0.40910938  0.0166108  -0.13580185  0.2287762  -1.0705658
 -1.3063427   1.9674747   1.2154671   1.4390606   1.6214067  -0.16860329] 

Pooled_max(Tensorflow): (1, 11, 1)
[ 0.16915537  0.0166108   0.0166108   0.2287762   0.2287762  -1.0705658
  1.9674747   1.9674747   1.4390606   1.6214067   1.6214067 ]

Pooled_max(Manual): (11,)
[ 0.16915537  0.0166108   0.0166108   0.2287762   0.2287762  -1.07056582
  1.9674747   1.9674747   1.43906057  1.62140667  1.62140667]



### 2. Average Pooling

In [23]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import AveragePooling1D

#Set length, pooling size, strides
L, f, s = 12, 2, 1

#Setting input
x = tf.random.normal(shape = (1, L, 1))

#Pooling (Tensorflow)
pool_avg = AveragePooling1D(pool_size = f, strides = s)
pooled_avg_tf = pool_avg(x)

#Pooling (Manual)
x = x.numpy().flatten()
pooled_avg_manual = np.zeros(shape = (L - f + 1, ))
for i in range(L - f + 1):
    window = x[i : i + f]
    pooled_avg_manual[i] = np.mean(window)

#Confirm
print("x : {}\n{} \n".format(x.shape, x))
print("Pooled_max(Tensorflow): {}\n{}\n".format(pooled_avg_tf.shape, pooled_avg_tf.numpy().flatten()))
print("Pooled_max(Manual): {}\n{}\n".format(pooled_avg_manual.shape, pooled_avg_manual))

x : (12,)
[ 0.7689024  -0.9118923  -0.5536972   0.92782885 -0.12280604  0.14109176
  0.31506255 -0.23213138 -0.6412913   0.00234941  0.46399724 -0.6675991 ] 

Pooled_max(Tensorflow): (1, 11, 1)
[-0.07149494 -0.73279476  0.18706581  0.40251142  0.00914286  0.22807716
  0.04146559 -0.43671134 -0.31947094  0.23317333 -0.10180092]

Pooled_max(Manual): (11,)
[-0.07149494 -0.73279476  0.18706581  0.40251142  0.00914286  0.22807716
  0.04146559 -0.43671134 -0.31947094  0.23317333 -0.10180092]



## 2. 2D Max/Avg Pooling

### 1. 2D Max Pooling

In [25]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 1, 5, 5, 1

#Set pooling size, strides
f, s = 2, 1

#Setting input
x = tf.random.normal(shape = (N, n_H, n_W, n_C))

#Pooling (Tensorflow)
pool_max = MaxPooling2D(pool_size = f, strides = s)
pooled_max_tf = pool_max(x)

#Pooling (Manual)
x = x.numpy().squeeze()
pooled_max_manual = np.zeros(shape = (n_H - f + 1, n_W - f + 1))
for h in range(n_H - f + 1):
    for w in range(n_W - f + 1):
        window = x[h : h + f, w : w + f]
        pooled_max_manual[h, w] = np.max(window)

#Confirm
print("x : {}\n{} \n".format(x.shape, x))
print("Pooled_max(Tensorflow): {}\n{}\n".format(pooled_max_tf.shape, pooled_max_tf.numpy().squeeze()))
print("Pooled_max(Manual): {}\n{}\n".format(pooled_max_manual.shape, pooled_max_manual))

x : (5, 5)
[[ 0.5248261   1.0258763  -0.15839802  2.6985228  -0.5771107 ]
 [ 0.34718257  0.35397738 -2.1478574  -1.203262    0.42150804]
 [-0.48967052  1.2312913  -1.3952584   1.547679    0.5735556 ]
 [ 0.24447973 -1.2603942  -0.81815    -0.35638398 -0.35499918]
 [-1.375884   -0.30685717 -0.48792428 -0.718564    1.0911018 ]] 

Pooled_max(Tensorflow): (1, 4, 4, 1)
[[ 1.0258763   1.0258763   2.6985228   2.6985228 ]
 [ 1.2312913   1.2312913   1.547679    1.547679  ]
 [ 1.2312913   1.2312913   1.547679    1.547679  ]
 [ 0.24447973 -0.30685717 -0.35638398  1.0911018 ]]

Pooled_max(Manual): (4, 4)
[[ 1.02587628  1.02587628  2.69852281  2.69852281]
 [ 1.23129129  1.23129129  1.54767895  1.54767895]
 [ 1.23129129  1.23129129  1.54767895  1.54767895]
 [ 0.24447973 -0.30685717 -0.35638398  1.09110177]]



### 2. 2D Average Pooling

In [26]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import AveragePooling2D

#Set minibatch, height, width, number of channel
N, n_H, n_W, n_C = 1, 5, 5, 1

#Set pooling size, strides
f, s = 2, 1

#Setting input
x = tf.random.normal(shape = (N, n_H, n_W, n_C))

#Pooling (Tensorflow)
pool_avg = AveragePooling2D(pool_size = f, strides = s)
pooled_avg_tf = pool_avg(x)

#Pooling (Manual)
x = x.numpy().squeeze()
pooled_avg_manual = np.zeros(shape = (n_H - f + 1, n_W - f + 1))
for h in range(n_H - f + 1):
    for w in range(n_W - f + 1):
        window = x[h : h + f, w : w + f]
        pooled_avg_manual[h, w] = np.mean(window)

#Confirm
print("x : {}\n{} \n".format(x.shape, x))
print("Pooled_avg(Tensorflow): {}\n{}\n".format(pooled_avg_tf.shape, pooled_avg_tf.numpy().squeeze()))
print("Pooled_avg(Manual): {}\n{}\n".format(pooled_avg_manual.shape, pooled_avg_manual))

x : (5, 5)
[[-0.04224042  0.37959704 -0.9280992  -0.5619632   0.03906506]
 [ 0.17953922 -0.25864312  0.4692503   1.6944262   0.84000456]
 [-1.1012747   1.5246391   0.7916912   0.8361347   1.799732  ]
 [-1.2689867  -1.1769449  -0.86608475 -0.63876826  0.59674907]
 [-0.78610855 -0.46532962 -0.8219392   1.1449747   0.56753314]] 

Pooled_avg(Tensorflow): (1, 4, 4, 1)
[[ 0.06456318 -0.08447377  0.1684035   0.5028832 ]
 [ 0.08606511  0.6317344   0.94787556  1.2925744 ]
 [-0.5056418   0.06832521  0.03074321  0.6484619 ]
 [-0.9243424  -0.8325746  -0.29545438  0.41762218]]

Pooled_avg(Manual): (4, 4)
[[ 0.06456318 -0.08447377  0.16840351  0.5028832 ]
 [ 0.08606511  0.63173437  0.94787556  1.29257441]
 [-0.50564182  0.06832521  0.03074321  0.64846188]
 [-0.92434239 -0.83257461 -0.29545438  0.41762218]]

