<a href="https://colab.research.google.com/github/krec7748/Fastcampus_DeepLearning/blob/main/CH01_03_Affine_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Affine Function

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[10.]]) #input setting (Note: input -> matrix shape)
dense = Dense(units = 1, activation = "linear") #imp.an affine function

y_tf = dense(x) #Forward propagation + params initialization

W, B = dense.get_weights()
y_matmul = tf.linalg.matmul(x, W) + B

print('========Input/Weight/Bias=========')
print("x : \n shape: {}\n value: {}\n".format(x.shape, x.numpy()))
print("W : \n shape: {}\n value: {}\n".format(W.shape, W))
print("B : \n shape: {}\n value: {}\n".format(B.shape, B))
print()
print('========Output/Weight/Bias=========')
print("y(Tensorflow): \n shape: {}\n value: {}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): \n shape: {}\n value: {}\n".format(y_matmul.shape, y_matmul.numpy()))

========Input/Weight/Bias=========
x : 
 shape: (1, 1)
 value: [[10.]]

W : 
 shape: (1, 1)
 value: [[0.71057546]]

B : 
 shape: (1,)
 value: [0.]


========Output/Weight/Bias=========
y(Tensorflow): 
 shape: (1, 1)
 value: [[7.105755]]

y(Manual): 
 shape: (1, 1)
 value: [[7.105755]]



## 2. Params initalization 

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

x = tf.constant([[10.]]) #input setting (Note: input -> matrix shape)
w, b = tf.constant([[10.]]), tf.constant([[20.]])

w_init, b_init = Constant(w), Constant(b)

dense = Dense(units = 1,
              activation = "linear",
              kernel_initializer = w_init,
              bias_initializer = b_init)

y_tf = dense(x)

print(y_tf)

W, B = dense.get_weights()

print("W : \n shape: {}\n value: {}\n".format(W.shape, W))
print("B : \n shape: {}\n value: {}\n".format(B.shape, B))

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W : 
 shape: (1, 1)
 value: [[10.]]

B : 
 shape: (1,)
 value: [20.]



## 3. Affine Function with n Features

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape = (1, 10), minval = 0, maxval = 10)

dense = Dense(units = 1) #activation default: "linear"

y_tf = dense(x)
W, B = dense.get_weights()

y_matmul = tf.linalg.matmul(x, W) + B

print('========Input/Weight/Bias=========')
print("x : \n shape: {}\n value: \n {}\n".format(x.shape, x.numpy()))
print("W : \n shape: {}\n value: \n {}\n".format(W.shape, W))
print("B : \n shape: {}\n value: {}\n".format(B.shape, B))
print()
print('========Output/Weight/Bias=========')
print("y(Tensorflow): \n shape: {}\n value: {}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): \n shape: {}\n value: {}\n".format(y_matmul.shape, y_matmul.numpy()))

========Input/Weight/Bias=========
x : 
 shape: (1, 10)
 value: 
 [[8.479128  5.2092276 5.501708  8.103451  9.480567  5.4695215 1.7207038
  7.6782093 5.703229  8.985534 ]]

W : 
 shape: (10, 1)
 value: 
 [[-0.01212406]
 [-0.5005395 ]
 [-0.18577212]
 [ 0.53700083]
 [-0.00329876]
 [ 0.14693314]
 [-0.35809702]
 [ 0.70418507]
 [ 0.12477314]
 [-0.14017153]]

B : 
 shape: (1,)
 value: [0.]


========Output/Weight/Bias=========
y(Tensorflow): 
 shape: (1, 1)
 value: [[5.6344457]]

y(Manual): 
 shape: (1, 1)
 value: [[5.6344457]]



## 4. Activation Layer

In [4]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape = (1, 5), seed = 2) #input setting

#imp. activation
sigmoid = Activation("sigmoid")
tanh = Activation("tanh")
relu = Activation("relu")

#Activation function (Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

#Activation function (Manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print("x \n shape: {} \n value: {} \n".format(x.shape,x.numpy()))
print()
print("sigmoid(Tensorflow) \n shape:{} \n value:{} \n".format(y_sigmoid_tf.shape,y_sigmoid_tf.numpy()))
print("sigmoid(manual) \n shape:{} \n value:{} \n".format(y_sigmoid_man.shape,y_sigmoid_man.numpy()))
print()
print("Tanh(Tensorflow) \n shape:{} \n value:{} \n".format(y_tanh_tf.shape,y_tanh_tf.numpy()))
print("Tanh(manual) \n shape:{} \n value:{} \n".format(y_tanh_man.shape,y_tanh_man.numpy()))
print()
print("ReLU(Tensorflow) \n shape:{} \n value:{} \n".format(y_relu_tf.shape,y_relu_tf.numpy()))
print("ReLU(manual) \n shape:{} \n value:{} \n".format(y_relu_man.shape,y_relu_man.numpy()))

x 
 shape: (1, 5) 
 value: [[-0.85811085 -0.19662298  0.13895045 -1.2212768  -0.40341285]] 


sigmoid(Tensorflow) 
 shape:(1, 5) 
 value:[[0.2977342  0.451002   0.5346818  0.22771186 0.40049264]] 

sigmoid(manual) 
 shape:(1, 5) 
 value:[[0.2977342  0.45100197 0.5346818  0.22771186 0.40049264]] 


Tanh(Tensorflow) 
 shape:(1, 5) 
 value:[[-0.69528306 -0.1941277   0.13806304 -0.84003043 -0.3828653 ]] 

Tanh(manual) 
 shape:(1, 5) 
 value:[[-0.69528306 -0.19412771  0.13806306 -0.8400304  -0.38286537]] 


ReLU(Tensorflow) 
 shape:(1, 5) 
 value:[[0.         0.         0.13895045 0.         0.        ]] 

ReLU(manual) 
 shape:(1, 5) 
 value:[[0.         0.         0.13895045 0.         0.        ]] 



## 5. Activation in Dense Layer

In [5]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape = (1, 5), seed = 2) #input setting

#imp. an affine + activation
dense_sigmoid = Dense(units = 1, activation = "sigmoid")
dense_tanh = Dense(units = 1, activation = "tanh")
dense_relu = Dense(units = 1, activation = "relu")

#Calculate activation value (Tensorflow)
y_sigmoid_tf = dense_sigmoid(x)
y_tanh_tf = dense_tanh(x)
y_relu_tf = dense_relu(x)

#Define function to get activation value (Manual)
def get_manual_activation_value(tf_x, tf_dense_with_activation, activation):
    W, B = tf_dense_with_activation.get_weights()
    z = tf.linalg.matmul(tf_x, W) + B
    if activation == "sigmoid":
        a = 1 / (1 + exp(-z))
    elif activation == "tanh":
        a = (exp(z) - exp(-z)) / (exp(z) + exp(-z))
    elif activation == "relu":
        a = maximum(z, 0)

    return a

#Calculate activation value (Manual)
y_sigmoid_man = get_manual_activation_value(x, dense_sigmoid, "sigmoid")
y_tanh_man = get_manual_activation_value(x, dense_tanh, "tanh")
y_relu_man = get_manual_activation_value(x, dense_relu, "relu")


#Confirm
print("<Sigmoid>")
print("Activation value(Tensorflow): \n shape: {} \n value: {}\n".format(y_sigmoid_tf.shape,y_sigmoid_tf.numpy()))
print("Activation value(manual): \n shape: {} \n value: {}\n".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))
print()
print("<Tanh>")
print("Activation value(Tensorflow): \n shape: {} \n value: {}\n".format(y_tanh_tf.shape,y_tanh_tf.numpy()))
print("Activation value(manual): \n shape: {} \n value: {}\n".format(y_tanh_man.shape, y_tanh_man.numpy()))
print()
print("<ReLU>")
print("Activation value(Tensorflow): \n shape: {} \n value: {}\n".format(y_relu_tf.shape,y_relu_tf.numpy()))
print("Activation value(manual): \n shape: {} \n value: {}\n".format(y_relu_man.shape, y_relu_man.numpy()))

<Sigmoid>
Activation value(Tensorflow): 
 shape: (1, 1) 
 value: [[0.43295142]]

Activation value(manual): 
 shape: (1, 1) 
 value: [[0.4329514]]


<Tanh>
Activation value(Tensorflow): 
 shape: (1, 1) 
 value: [[-0.9548702]]

Activation value(manual): 
 shape: (1, 1) 
 value: [[-0.95487016]]


<ReLU>
Activation value(Tensorflow): 
 shape: (1, 1) 
 value: [[0.]]

Activation value(manual): 
 shape: (1, 1) 
 value: [[0.]]



## 6. Minibatch

In [6]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 16, 10 #set input params
x = tf.random.normal(shape = (N, n_feature)) #generate minibatch

dense = Dense(units = 1, activation = "relu") #imp. an AN
y = dense(x) #Forward propagation

W, B = dense.get_weights() #get weight, bias

#print results
print("shape of x : ", x.shape)
print("shape of W : ", W.shape)
print("shape of B : ", B.shape)

shape of x :  (16, 10)
shape of W :  (10, 1)
shape of B :  (1,)


In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 #set input params
x = tf.random.normal(shape = (N, n_feature)) #generate minibatch

dense = Dense(units = 1, activation = "sigmoid") #imp. an AN
a_tf = dense(x) #forward propagation (Tensorflow)

W, B = dense.get_weights() #get weight, bias

z_man = tf.linalg.matmul(x, W) + B #forward propagation_01 (Manual) - Affine function
a_man = 1 / (1 + exp(-z_man)) #forward propagation_02 (Manual) - Activation function

#print results
print("Output(Tensorflow) : \n {}\n".format(a_tf.numpy()))
print("Output(Manual) : \n {}\n".format(a_man.numpy()))

Output(Tensorflow) : 
 [[0.28788725]
 [0.45299008]
 [0.84574205]
 [0.8148756 ]
 [0.890126  ]
 [0.42632514]
 [0.461335  ]
 [0.48884308]]

Output(Manual) : 
 [[0.28788725]
 [0.45299008]
 [0.845742  ]
 [0.8148756 ]
 [0.89012593]
 [0.4263251 ]
 [0.46133503]
 [0.48884308]]

